//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_All_Certificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Certification = new HashSet<Certification>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
    
        public virtual ICollection<Certification> Certification { get; set; }
    }
}
