//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_All_Certificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoist
    {
        public string Productkey { get; set; }
        public string Description { get; set; }
        public string Dimensions { get; set; }
        public string Material { get; set; }
        public string Heattreatment { get; set; }
        public string ProofloadApplied { get; set; }
        public string WorkingLoadLimit { get; set; }
        public string SafetyFactor { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
