//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_All_Certificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Certifications = new HashSet<Certification>();
        }
    
        public int InventoryID { get; set; }
        public string ProductKey { get; set; }
    
        public virtual ICollection<Certification> Certifications { get; set; }
        public virtual Product Product { get; set; }
    }
}
