
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace Rent_All_Certificate.Models
{

    using System.Collections.Generic;
    
    public partial class Manufacturer
    {

        public Manufacturer()
        {

            this.Product = new HashSet<Product>();

        }
    

        public int ManufacturerID { get; set; }

        public string ManufacturerName { get; set; }
    


        public virtual ICollection<Product> Product { get; set; }

    }

    [MetadataType(typeof(ManufacturerMetaData))]
    public partial class Manufacturer
    {
        
    }

    public class ManufacturerMetaData
    {
        [Required]
        [Display(Name = "Manufacturer")]
        public string ManufacturerName { get; set; }
    }
}
