
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rent_All_Certificate.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Nen3140
{

    public int CertificateID { get; set; }

    public Nullable<int> InventoryID { get; set; }

    public Nullable<int> BranchID { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public System.DateTime Date { get; set; }

    public string File { get; set; }



    public virtual Certification Certification { get; set; }

}

}
