
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rent_All_Certificate.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public Product()
    {

        this.Inventory = new HashSet<Inventory>();

    }


    public string ProductKey { get; set; }

    public int PhaseID { get; set; }

    public int CategoryID { get; set; }

    public int ManufacturerID { get; set; }

    public string ProductName { get; set; }



    public virtual Category Category { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual Phase Phase { get; set; }

}

}
