

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rent_All_Certificate.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RentAllEntities : DbContext
{
    public RentAllEntities()
        : base("name=RentAllEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Branch> Branch { get; set; }

    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Certification> Certification { get; set; }

    public virtual DbSet<City> City { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<Hoist> Hoist { get; set; }

    public virtual DbSet<Inventory> Inventory { get; set; }

    public virtual DbSet<Manufacturer> Manufacturer { get; set; }

    public virtual DbSet<Nen3140> Nen3140 { get; set; }

    public virtual DbSet<Phase> Phase { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<CertificationLog> CertificationLog { get; set; }

}

}

